apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: ivo-test-ns ###  Create namespace[kubectl create ns] before you run the [kubectl apply -f nginx-pod.yaml] 
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
  image: nginx:latest
  ports:
  - containerPort: 80