apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80