apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-ivo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /tmp/demo-ivo-pv